### ISSUE TITLE
Question:  How to fetch the nugetforunity packages during CI/CD in a github action?  

### ISSUE THREAD

**Issue by gotchipete** [GlitchEnzo/NuGetForUnity#522]
Has anyone done this?

**Comment by JoC0de** [comment]
Hi,
In the CI of NuGetForUnity we use it to verify that it works.
https://github.com/GlitchEnzo/NuGetForUnity/blob/03353e7a94bd01ef6daa80e3a5fd85c7f5fa4725/.github/workflows/main.yml#L207-L211
Note: When you do it in your own CI you don't need the `--add-source`.

**Comment by JoC0de** [comment]
See also the documentation in the [ReadMe.md](https://github.com/GlitchEnzo/NuGetForUnity#restoring-nuget-packages-over-the-command-line). I thought that this is "enough" to understand how to use it in CI/CD. Do you have any suggestion on how we can improve the documentation?

**Comment by gotchipete** [comment]
Not sure yet how to improve it but I'm trying to follow it unsuccessfully as well (including the comments in this thread)

**Comment by gotchipete** [comment]
aha this is working but i have an issue with one of my packages now.  @JoC0de if there is a way i can improve this lmk

```
      # setup .NET for package resolution
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      # Install NuGetForUnity.Cli
      - name: Restore dotnet tool - NuGetForUnity.Cli
        run: dotnet new tool-manifest; dotnet tool install NuGetForUnity.Cli

      # Restore NuGetForUnity packages
      - name: Restore NuGetForUnity packages
        run: dotnet nugetforunity restore ./apps/gotchiverse-unity
```
